version: "3"
services:
  datadog-api-client-v1:
    image: datadog/docker-library:openapi-generator-cli-60b29e1f8e2
    user: "${UID}:${GID}"
    volumes:
      - .:/src:rw
    working_dir: /src
    command:
      - /usr/local/bin/docker-entrypoint.sh
      - generate
      - -g
      - "java"
      - -c
      - ".generator/config/v1.json"
      - -i
      - ".generator/schemas/v1/openapi.yaml"
      - -o
      - "./v1"
      - --additional-properties
      - java8=true,dateLibrary=java8
      - --global-property
      - skipFormModel=false
      - --type-mappings
      - AnyType=Object
      - -t
      - ".generator/templates"
  datadog-api-client-v2:
    image: datadog/docker-library:openapi-generator-cli-60b29e1f8e2
    user: "${UID}:${GID}"
    volumes:
      - .:/src:rw
    working_dir: /src
    command:
      - /usr/local/bin/docker-entrypoint.sh
      - generate
      - -g
      - "java"
      - -c
      - ".generator/config/v2.json"
      - -i
      - ".generator/schemas/v2/openapi.yaml"
      - -o
      - "./v2"
      - --additional-properties
      - java8=true,dateLibrary=java8
      - --global-property
      - skipFormModel=false
      - --type-mappings
      - AnyType=Object
      - -t
      - ".generator/templates"
