name: Send PR Approval Status

on:
  pull_request:
    branches:
      - master
    types: ["review_requested", "synchronize", "opened", "reopened"]
  pull_request_review:
    types:
      - submitted
      - dismissed

jobs:
  send_status:
    permissions:
      contents: read
      id-token: write  # Required for dd-octo-sts OIDC token
    runs-on: ubuntu-latest
    if: >
      github.event.pull_request.draft == false &&
      !contains(github.event.pull_request.labels.*.name, 'ci/skip') &&
      !contains(github.event.pull_request.head.ref, 'datadog-api-spec/test/') &&
      contains(github.event.pull_request.head.ref, 'datadog-api-spec/generated/')
    steps:
      - name: Get GitHub token via dd-octo-sts
        id: get_token
        uses: DataDog/dd-octo-sts-action@acaa02eee7e3bb0839e4272dacb37b8f3b58ba80  # v1.0.3
        with:
          scope: DataDog/datadog-api-spec
          policy: datadog-api-client-java.approved_status.post-review-status
      - name: Post PR review status check
        uses: DataDog/github-actions/post-review-status@v2
        with:
          github-token: ${{ steps.get_token.outputs.token }}
          repo: datadog-api-spec
          context: datadog-api-client-java/master
