name: Reusable Shading Workflow

on:
  workflow_call:
    inputs:
      target-branch:
        description: 'Branch to checkout and test (defaults to the calling branch)'
        required: false
        type: string
        default: ''
      java-version:
        description: 'Java version to use for shading check'
        required: false
        type: string
        default: '8'

jobs:
  shading:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: DataDog/datadog-api-client-java
          ref: ${{ inputs.target-branch || github.ref }}
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: "temurin"
          cache: "maven"
      - name: Check all dependencies shaded
        run: ./shade-test.sh