name: Reusable Examples Workflow

on:
  workflow_call:
    inputs:
      target-branch:
        description: 'Branch to checkout and test (defaults to the calling branch)'
        required: false
        type: string
        default: ''
      examples-script:
        description: 'Examples script to execute'
        required: false
        type: string
        default: './check-examples.sh'
      java-version:
        description: 'Java version to use for examples'
        required: false
        type: string
        default: '16'

jobs:
  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: DataDog/datadog-api-client-java
          ref: ${{ inputs.target-branch || github.ref }}
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: "temurin"
          cache: "maven"
      - name: Check examples
        run: ${{ inputs.examples-script }}
        shell: bash