name: Reusable Complete CI Workflow

on:
  workflow_call:
    inputs:
      target-branch:
        description: 'Branch to checkout and test (defaults to the calling branch)'
        required: false
        type: string
        default: ''
      java-versions:
        description: 'JSON array of Java versions to test against'
        required: false
        type: string
        default: '["8", "16", "18", "19"]'
      platforms:
        description: 'JSON array of platforms to run tests on'
        required: false
        type: string
        default: '["ubuntu-latest"]'
      test-script:
        description: 'Test script to execute'
        required: false
        type: string
        default: './run-tests.sh'
      examples-script:
        description: 'Examples script to execute'
        required: false
        type: string
        default: './check-examples.sh'
    secrets:
      # Integration test secrets
      DD_API_KEY:
        required: false
      DD_CLIENT_API_KEY:
        required: false
      DD_CLIENT_APP_KEY:
        required: false
      SLEEP_AFTER_REQUEST:
        required: false

jobs:
  pre-commit:
    uses: ./.github/workflows/reusable-pre-commit.yml
    with:
      target-branch: ${{ inputs.target-branch }}
      enable-commit-changes: false  # Don't auto-commit in external CI

  javadoc:
    uses: ./.github/workflows/reusable-javadoc.yml
    with:
      target-branch: ${{ inputs.target-branch }}

  shading:
    uses: ./.github/workflows/reusable-shading.yml
    with:
      target-branch: ${{ inputs.target-branch }}

  test:
    uses: ./.github/workflows/reusable-java-test.yml
    with:
      target-branch: ${{ inputs.target-branch }}
      java-versions: ${{ inputs.java-versions }}
      platforms: ${{ inputs.platforms }}
      test-script: ${{ inputs.test-script }}
    secrets:
      DD_API_KEY: ${{ secrets.DD_API_KEY }}

  examples:
    uses: ./.github/workflows/reusable-examples.yml
    with:
      target-branch: ${{ inputs.target-branch }}
      examples-script: ${{ inputs.examples-script }}

  integration:
    uses: ./.github/workflows/reusable-integration-test.yml
    with:
      target-branch: ${{ inputs.target-branch }}
      has-integration-label: ${{ contains(github.event.pull_request.labels.*.name, 'ci/integrations') }}
    secrets:
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
      DD_CLIENT_API_KEY: ${{ secrets.DD_CLIENT_API_KEY }}
      DD_CLIENT_APP_KEY: ${{ secrets.DD_CLIENT_APP_KEY }}
      SLEEP_AFTER_REQUEST: ${{ secrets.SLEEP_AFTER_REQUEST }}

